when:
- event: tag

clone:
- image: woodpeckerci/plugin-git
  settings:
    recursive: true
    partial: false

steps:
- image: rkrc/curl-jq:latest
  commands:
  - ./bin/woodpecker/event/tag/release.sh
  - ./bin/woodpecker/event/tag/release-info.sh
