when:
- event: tag

clone:
- name: $CI_REPO
  image: woodpeckerci/plugin-git
  settings:
    recursive: true
    partial: false

environment:
  TOKEN:
    from_secret: CHICKEN_SCHEME_RELEASE_INFO_TOKEN

steps:
- name: release and release-info
  image: rkrc/curl-jq:latest
  commands:
  - ./bin/woodpecker/event/tag/release.sh
  - ./bin/woodpecker/event/tag/release-info.sh
